### ISSUE TITLE
Win32Crypt not found on pip / python 3.9.13

### ISSUE THREAD

**Issue by TEnLOcODE** [AstraaDev/Discord-Token-Grabber-V2#12]
``Traceback (most recent call last):
  File "C:/Users/Olga&Boris/token-grabber.py", line 3, in <module>
    from win32crypt import CryptUnprotectData
ModuleNotFoundError: No module named 'win32crypt'``

um.. i can not find any packages that contain/is win32crypt.. help?..

**Comment by Ghost-Boy-007** [comment]
First:          curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py 
Second:     python3 get-pip.py

**Comment by Tulip-0333** [comment]
That didn't work for me @Ghost-Boy-007

**Comment by Ghost-Boy-007** [comment]
idk, bc that worked for me. You prob dont have python or bash installed

**Comment by Ghost-Boy-007** [comment]
Did you type in the exact stuff without the "First:" and the "Second:"

**Comment by Ghost-Boy-007** [comment]
Also u need to have python and bash installed,maybe homebrew idk tbh

**Comment by AntonioSaysFuckYou** [comment]
pip install pypiwin32
this seems to work for me (:
