### ISSUE TITLE
How would i use this?!

### ISSUE THREAD

**Issue by SyriaIsFake** [AstraaDev/Discord-Token-Grabber-V2#14]
If my victim was to run this they would have to install all these modules? also converting it to an executable wouldn't work, may i please know how i could maybe bundle all these modules into one folder or file so I can get the said victim to run it without installing so many modules. Im not too good with python and was wondering if there is a solution (:

**Comment by Ju2t-us** [comment]
> If my victim was to run this they would have to install all these modules? also converting it to an executable wouldn't work, may i please know how i could maybe bundle all these modules into one folder or file so I can get the said victim to run it without installing so many modules. Im not too good with python and was wondering if there is a solution (:

Yeah, I'm wondering this same thing...

**Comment by SyriaIsFake** [comment]
> did you get your answer?

I still have no solution. I've tried multiple things such as py2exe and other methods and nothing seems to work.

**Comment by Joshua11TheHacker** [comment]
you can like convert it into a rat for minecraft

**Comment by jven123** [comment]
did you enter ur webhook url?

**Comment by jven123** [comment]
install all modules tht are needed and also convert into exe and enter ur webhook url
and victims no need to install modules xd
