### ISSUE TITLE
line 9, in <module> import requests, json, os ModuleNotFoundError: No module named 'requests'

### ISSUE THREAD

**Issue by bepdop** [AstraaDev/Discord-Token-Grabber-V2#17]
i have installed Cryptodome and win32crypt but still get this error

**Comment by bepdop** [comment]
found a fix, just had to pip install requests

**Comment by FazeImRoo** [comment]
> 

how do u do that?

**Comment by Ju2t-us** [comment]
> > 
> 
> how do u do that?

Simply open up your command line and type in `pip install requests` 
This may or may not work on linux systems.
