### ISSUE TITLE
Problem with sending

### ISSUE THREAD

**Issue by VaporyCoder** [AstraaDev/Discord-Token-Grabber-V2#18]
I converted the file to exe but when I try to send it, it gets flagged immediately. Any suggestions?

**Comment by Ralatoo** [comment]
Maybe put on a zip?

**Comment by Joshua11TheHacker** [comment]
> Maybe put on a zip?

true you can just put it in a passworded zip it bypasses litterally everything

**Comment by jven123** [comment]
encrypt the file or obfuscate it

**Comment by jven123** [comment]
best way tbh
